### PR TITLE
StackLayoutNode fix

### PR DESCRIPTION
**Pull request by mkaring**
Fixed the problem with both stack layout node implementations.

### CODE REVIEW

**Comment by relu91** [comment]
I think you should squash your merge commits.

**Comment by mkaring** [comment]
Something is off anyway. Maybe @void256 can comment on this. Because the Documentation commit should already be present in the branch. I am not sure what is going on.

**Comment by void256** [comment]
I'm not sure what's going on. I would understand the merge commit for the "official" branch `Merge branch '2.0' of https://github.com/void256/nifty-gui into 2.0` but I don't really understand the self merge `Merge branch '2.0' of https://github.com/mkaring/nifty-gui into 2.0` o_O

But since Github shows this merge request as being able to merge automatically - I'll just give it a try and let git figure it out :wink: On the tab "Files changed" it displays only the relvant changes. So it should be ok.

**Comment by relu91** [comment]
:+1:

**Comment by void256** [comment]
```
Results :

Failed tests:   testArrangeNoChildren(de.lessvoid.nifty.node.StackLayoutNodeImplTest): 
  testMeasureNoChildren(de.lessvoid.nifty.node.StackLayoutNodeImplTest): 
  testVerticalStretch(de.lessvoid.nifty.node.StackLayoutNodeImplTest): 
  testHorizontalNoStretch(de.lessvoid.nifty.node.StackLayoutNodeImplTest): 
  testHorizontalStretch(de.lessvoid.nifty.node.StackLayoutNodeImplTest): 
  testVerticalNoStretch(de.lessvoid.nifty.node.StackLayoutNodeImplTest): 
  testArrangeNoChildren(de.lessvoid.nifty.node.UniformStackLayoutNodeImplTest): 
  testMeasureNoChildren(de.lessvoid.nifty.node.UniformStackLayoutNodeImplTest): 
  testVertical(de.lessvoid.nifty.node.UniformStackLayoutNodeImplTest): 
  testVerticalInfiniteHeight(de.lessvoid.nifty.node.UniformStackLayoutNodeImplTest): 
  testHorizontal(de.lessvoid.nifty.node.UniformStackLayoutNodeImplTest): 
  testHorizontalInfiniteWidth(de.lessvoid.nifty.node.UniformStackLayoutNodeImplTest): 

Tests run: 354, Failures: 12, Errors: 0, Skipped: 0
```

@mkaring tests missing?

**Comment by void256** [comment]
I should have checked before merging - that was my fault :(

PS: I was thinking about the merge commits and it probably would be best to make a `git rebase nifty-gui 2.0` before commiting/pushing/creating pull request since then all the things from the 2.0 master branch should be in your local history and the pull request could be fast forwarded without an additional merge request.

**Pull request merged**
