### PR TITLE
Adding nifty-renderer-processing to nifty

### PR DESCRIPTION
**Pull request by barefists**
Implementation of RenderDevice and InputSystem for Processing 2.*

A simple implementation of RenderDevice for Processing wrapped around the Java2D renderer, but using Processing's own VLW bitmap font format. Also included is an implementation of InputSystem for Processing's proprietary input event classes.

I also needed to change access of AwtToNiftyKeyCodeConverter in the Java2D renderer package to public for use in implementing the input system. Let me know if this is okay.

### CODE REVIEW

**Comment by spaceemotion** [comment]
Are the eclipse files necessary?

**Comment by barefists** [comment]
Oh, not really. I'll add them to .gitignore - sorry about that.

**Comment by bgroenks96** [comment]
@void256 Why has this PR been sitting here for so long?

**Comment by void256** [comment]
Waaaah! I think I agreed with spaceemotion that the eclipse files shouldn't be part of the commit .. and then somehow didn't notice barefists changes!

My apologies!

**Comment by dominic-jones** [comment]
I am still noticing eclipse files in the nifty-minim-soundsystem directory. Also, mvn clean install is not running from the project root. Claims it cannot find that new soundsystem module. Might be my setup though. Investigating.

**Comment by void256** [comment]
_argh_ :smile: already cleaned that up too!

**Comment by barefists** [comment]
Seems processing is gradually depreciating Java2D over JavaFX in the latest 3.0.1 version. Guess it's time to revise the Processing renderer to better support the changes. If you are trying to use the current renderer in 3.0.1, you'll run into issues, it still works well for 2.2.1 though.

**Pull request merged**
