### PR TITLE
SizeValue refactoring and wildcard text wrapping

### PR DESCRIPTION
**Pull request by Joris-van-der-Wel**
I wanted a chat control with word wrap. This does not work for a couple of reasons. This pull request will make it possible:
1. A refactoring of SizeValue so that a null value is now a real value (width="default" or width="d"), this avoids "== null" checks.
2. A refactoring of SizeValue so that values that are computed (like in preProcessConstraintWidthThisLevel) do not have to store additional state somewhere. For example if the "default" value is used (which does a sum or max when using HorizontalLayout for example), the SizeValue will tell you the computed pixel value, but also that the computation was part of the "default" value.
3. Two new size values "sum" and "max", this is similar to the behaviour that was already present, namely compute the total/maximum heights of the children. These values are useful when you would like to be explicit. It also lets you use sum/max in any layout.
4. Text elements now support width="*" (wildcard) in horizontal layouts in combination with word wrap. This also lets you have parent panels that automatically base their height on these text elements. This allows for reimplementing the chat control using a ScrollPanel instead of a ListBox so that chat lines can wrap AND have player images. See issue #169

I also wrote test cases to test for this new behaviour.
I did my best to ensure backwards compatability. All the test cases pass, and I compared all the examples with a nifty-gui without these changes. (Although a few examples do not work, and "ControlsDemo" only seems to work on my AMD gpu, but not on my laptop with nvidia)

I made an example that shows you how these changes could implement a new chat control:

``` xml
<panel width="423" childLayout="vertical" backgroundColor="#444f" align="center" valign="center">
        <control id="scrollbarPanel" style="special-scrollpanel" name="scrollPanel" horizontal="false" height="400" width="100%">
                <panel id="myScrollStuff" width="100%" childLayout="vertical">
                        <panel width="100%" height="max" backgroundColor="#f00f" childLayout="horizontal" align="center">
                                <panel valign="top" backgroundColor="#0f0f" width="60" height="20"/>
                                <text valign="center" width="*" style="nifty-label" backgroundColor="#00ff" color="#000f" wrap="true" text="Ut non pretium urna. Ut faucibus diam eu commodo auctor. Phasellus lobortis felis eu velit blandit, quis volutpat turpis dictum. Vivamus massa nibh, dignissim non fringilla vitae, euismod sit amet lacus. Duis tristique, dui non consequat tempus, justo nunc feugiat sapien, eu ornare ligula turpis eu velit."/>
                                <panel valign="center" backgroundColor="#0f0f" width="20" height="30"/>
                                <text valign="center" width="*" style="nifty-label" backgroundColor="#00ff" color="#000f" textHAlign="left" wrap="false" text="I have newlines but no wrap!. ${CALL.newline()} Ut faucibus diam eu commodo auctor. Phasellus lobortis felis eu velit blandit, quis volutpat turpis dictum. Vivamus massa nibh, dignissim non fringilla vitae, euismod sit amet. ${CALL.newline()}Lacus!"/>
                        </panel>
                        <panel height="50"/>
                        <panel width="100%" height="max" backgroundColor="#f00f" childLayout="horizontal" align="center">
                                <panel valign="center" backgroundColor="#0f0f" width="60" height="60"/>
                                <text valign="center" width="*" style="nifty-label" backgroundColor="#00ff" color="#000f" wrap="true" text="Ut non pretium urna. Ut faucibus diam eu commodo auctor. Phasellus lobortis felis eu velit blandit, quis volutpat turpis dictum. Vivamus massa nibh, dignissim non fringilla vitae, euismod sit amet lacus. Duis tristique, dui non consequat tempus, justo nunc feugiat sapien, eu ornare ligula turpis eu velit."/>
                        </panel>
                        <panel height="50"/>
                        <panel width="100%" height="max" backgroundColor="#f00f" childLayout="horizontal" align="center">
                                <text valign="center" width="*" style="nifty-label" backgroundColor="#00ff" color="#000f" wrap="true" text="Ut non pretium urna. Ut faucibus diam eu commodo auctor. Phasellus lobortis felis eu velit blandit, quis volutpat turpis dictum. Vivamus massa nibh, dignissim non fringilla vitae, euismod sit amet lacus. Duis tristique, dui non consequat tempus, justo nunc feugiat sapien, eu ornare ligula turpis eu velit."/>
                                <panel valign="top" backgroundColor="#0f0f" width="60" height="60"/>
                        </panel>
                        <panel height="50"/>
                        <panel width="100%" height="max" backgroundColor="#f00f" childLayout="horizontal" align="center">
                                <text valign="center" width="*" style="nifty-label" backgroundColor="#00ff" color="#000f" wrap="true" text="Ut non pretium urna. Ut faucibus diam eu commodo auctor. Phasellus lobortis felis eu velit blandit, quis volutpat turpis dictum. Vivamus massa nibh, dignissim non fringilla vitae, euismod sit amet lacus. Duis tristique, dui non consequat tempus, justo nunc feugiat sapien, eu ornare ligula turpis eu velit."/>                                
                        </panel>
                </panel>
        </control>
</panel>
```

And here is a screenshot (the green squares represent what would be the image):
nifty-wildcard-text

### CODE REVIEW

**Comment by ghost** [comment]
> Although a few examples do not work, and "ControlsDemo" only seems to work on my AMD gpu, but not on my laptop with nvidia

I don't know about @void256 but this statement scares me.

**Comment by ghost** [comment]
> All the test cases pass

Every example in the nifty-examples module is an **integration test**. So no, all the test cases are not passing.

**Comment by Joris-van-der-Wel** [comment]
Just to be clear, those examples never worked for me. Even before I touched a single character of code. So I am not sure how I can test those.
I can add issues for these if you would like?

All of these are _without_ my changes:

TutorialMainNativeLwjgl gives me org.lwjgl.LWJGLException: Could not create context (WGL_ARB_create_context).

ResolutionExampleMaindoes changes the resolution but does not update the size or position of the nifty stuff.\

TableExampleMain works, except no text is displayed and I get WARNING [de.lessvoid.nifty.controls.listbox.ListBoxControl] Unable to instantiate given class [de.lessvoid.nifty.examples.table.TableRowViewConverter] with error: Class de.lessvoid.nifty.controls.listbox.ListBoxControl can not access a member of class de.lessvoid.nifty.examples.table.TableRowViewConverter with modifiers ""
WARNING [de.lessvoid.nifty.controls.ListBox$ListBoxViewConverterSimple] you're using the ListBoxViewConverterSimple but there is no TextRenderer on the listBoxElement.You've probably changed the item template but did not provided your own ListBoxViewConverter to the ListBox.

**Comment by ghost** [comment]
> Just to be clear, those examples never worked for me. Even before I touched a single character of code. So I am not sure how I can test those.
> I can add issues for these if you would like?
> 
> All of these are without my changes:
> 
> TutorialMainNativeLwjgl gives me org.lwjgl.LWJGLException: Could not create context (WGL_ARB_create_context).
> 
> ResolutionExampleMaindoes changes the resolution but does not update the size or position of the nifty stuff.\
> 
> TableExampleMain works, except no text is displayed and I get WARNING [de.lessvoid.nifty.controls.listbox.ListBoxControl] Unable to instantiate given class [de.lessvoid.nifty.examples.table.TableRowViewConverter] with error: Class de.lessvoid.nifty.controls.listbox.ListBoxControl can not access a member of class de.lessvoid.nifty.examples.table.TableRowViewConverter with modifiers ""
> WARNING [de.lessvoid.nifty.controls.ListBox$ListBoxViewConverterSimple] you're using the ListBoxViewConverterSimple but there is no TextRenderer on the listBoxElement.You've probably changed the item template but did not provided your own ListBoxViewConverter to the ListBox.

Interesting. I don't use Lwjgl directly anymore so I don't know anything about that, but if you could submit issues for those, that would be great.

**Comment by ghost** [comment]
> Two new size values "sum" and "max", this is similar to the behaviour that was already present, namely compute the total/maximum heights of the children. These values are useful when you would like to be explicit. It also lets you use sum/max in any layout.

@Joris-van-der-Wel The sum and max ideas confuse the hell out of me. What's the difference between height="*" and height="max"? The asterisk is a greedy quantifier, i.e., it already attempts to use the "max" possible height.

I still have no clue after reading your description what height="sum" does either. Could you please explain these in more depth? Thanks.

> Text elements now support width="*" (wildcard) in horizontal layouts in combination with word wrap. This also lets you have parent panels that automatically base their height on these text elements. This allows for reimplementing the chat control using a ScrollPanel instead of a ListBox so that chat lines can wrap AND have player images. See issue #169 

This part makes perfect sense, and sounds like a great feature.

> This allows for reimplementing the chat control using a ScrollPanel instead of a ListBox

I would suggest doing that yourself if you have time as @void256 has very little, and I've implemented my own custom chat control with text wrapping that would not be as feature-rich as what you're suggesting here. I basically use the ListBox-style chat control, but I implemented a custom controller that calculates the width of a submitted chat message and splits it into multiple messages based on the constraint width of the listbox (including any padding). If you're interested I could show you my code, but again, it's not anywhere near the scale of changes and features that you are proposing, but then again, it's much simpler and therefore less prone to unexpected bugs ;).

**Comment by Joris-van-der-Wel** [comment]
>  The sum and max ideas confuse the hell out of me. What's the difference between height="*" and height="max"? The asterisk is a greedy quantifier, i.e., it already attempts to use the "max" possible height.
> I still have no clue after reading your description what height="sum" does either. Could you please explain these in more depth? Thanks.

Conceptually: An element with a wildcard calculates that size using its siblings.

``` XML
<panel childLayout="horizontal" width="100">
    <panel width="20"/>
    <panel width="*"/> <!-- actual width = 80 -->
</panel>
```

Max and sum base the size on their children, without ever looking at the parent or siblings.

``` XML
<panel childLayout="..." height="sum"> <!-- actual height = sum(20,45,10) = 20+45+10 = 85 -->
    <panel height="20"/>
    <panel height="45"/>
    <panel height="10"/>
</panel>

<panel childLayout="..." height="max"> <!-- actual height = max(20,45,10) = 45 -->
    <panel height="20"/>
    <panel height="45"/>
    <panel height="10"/>
</panel>
```

They are similar to functionality that was already present (in fact i use the same methods to compute them), but it makes it explicit. 
I made these because when I was starting out with nifty the null width and null height really confused me in the beginning and caused me a lot of time spent tinkering to get it right. It is also not possible to override a width attribute using a style so that it uses the null/default sizing.

It was not until I read the source of nifty that I really understood this:

``` XML
<panel childLayout="horizontal'> <!-- height is not given (null). actual height = max(50,80)  = 80 -->
   <panel height="50"/>
   <panel height="80"/>
</panel>

<panel childLayout="horizontal'> <!-- width is not given (null). actual width = sum(50,80)  = 130 -->
   <panel width="50"/>
   <panel width="80"/>
</panel>

<panel childLayout="horizontal'> <!-- width is not given (null). actual width = 0 -->
   <panel width="50"/>
   <panel width="80"/>
   <panel width="5%"/> <-- A non pixel value breaks this functionality, making it hard to debug what is going on -->
</panel>
```

I will look at filing those issues and the chat control when I have more time.

I am worried about breaking existing uses of the default chat control if I convert it from listbox to listpanel. Wouldn't existing styles mess up? Is this bad? Maybe I should create a secondary chat control, but this would lead to code duplication?

Your solution does sound less error prone, but you have to bite the bullet at some point, right. :p

**Comment by ghost** [comment]
> Maybe I should create a secondary chat control, but this would lead to code duplication?

@void256 prefers to deprecate first rather than replace. It's a compromise between replacement and duplication. We could deprecate the current chat control and create a new one. I believe that @void256 would be okay with that. He'll probably comment on this soon - usually he is on irc freenode #niftygui around 22:00 UTC if you want to get his attention or talk in more detail.

**Comment by ghost** [comment]
> Your solution does sound less error prone, but you have to bite the bullet at some point, right. :p

Actually, I prefer the listbox solution because I don't like having fine-grained scrolling in my chat box. This way, there are always a set number of fully-visible lines available, which is neater imo than the scrollpanel solution. Actually the TWL library uses the ScrollPanel-style by default I believe (or used to back when I tried it out some years ago).

So instead of deprecating it, we could have a ListBoxChatControl & ScrollPanelChatControl. I'm still probably going to PR my ListBox chat control text wrapping at some point.

**Comment by ghost** [comment]
>  Joris-van-der-Wel commented 30 minutes ago
> 
> > The sum and max ideas confuse the hell out of me. What's the difference between height="*" and height="max"? The asterisk is a greedy quantifier, i.e., it already attempts to use the "max" possible height.
> > I still have no clue after reading your description what height="sum" does either. Could you please explain these in more depth? Thanks.
> 
> Conceptually: An element with a wildcard calculates that size using its siblings.
> 
> ```
> <panel childLayout="horizontal" width="100">
>     <panel width="20"/>
>     <panel width="*"/> 
> </panel>
> ```
> 
> Max and sum base the size on the their children, without ever looking at the parent or siblings.
> 
> ```
> <panel childLayout="..." height="sum"> 
>     <panel height="20"/>
>     <panel height="45"/>
>     <panel height="10"/>
> </panel>
> 
> <panel childLayout="..." height="max"> 
>     <panel height="20"/>
>     <panel height="45"/>
>     <panel height="10"/>
> </panel>
> ```
> 
> They are similar to functionality that was already present (in fact i use the same methods to compute them), but it makes it explicit. 
> I made these because when I was starting out with nifty the null width and null height really confused me in the beginning and caused me a lot of time spent tinkering to get it right. It is also not possible to override a width attribute using a style so that it uses the null/default sizing.
> 
> It was not until I read the source of nifty that I really understood this:
> 
> ```
> <panel childLayout="horizontal'> 
>    <panel height="50"/>
>    <panel height="80"/>
> </panel>
> <panel childLayout="horizontal'> 
>    <panel width="50"/>
>    <panel width="80"/>
> </panel>
> <panel childLayout="horizontal'> 
>    <panel width="50"/>
>    <panel width="80"/>
>    <panel width="5%"/> <-- A non pixel value breaks this functionality, making it hard to debug what is going on -->
> </panel>
> ```
> 
> I will look at filing those issues and the chat control when I have more time.
> 
> I am worried about breaking existing uses of the default chat control if I convert it from listbox to listpanel. Wouldn't existing styles mess up? Is this bad? Maybe I should create a secondary chat control, but this would lead to code duplication?
> 
> Your solution does sound less error prone, but you have to bite the bullet at some point, right. :p

Ah, it's all clear now. Does not specifying the width and/or height still work as expected? What about images instead of panels, and images within panels? Are those properly dealt with under this improved system?

**Comment by ghost** [comment]
> Ah, it's all clear now. Does not specifying the width and/or height still work as expected? What about images instead of panels, and images within panels? Are those properly dealt with under this improved system?

I'm also wondering about layers.

My point is that there are other elements than just panels, and they all need to work as expected under this new/improved system. I'm not sure if you took them into account or tested them.

**Comment by ghost** [comment]
> I'm also wondering about layers.

Sorry about that, actually it seems that layers can only be the size of the screen itself.

**Comment by ghost** [comment]
> we could have a ListBoxChatControl & ScrollPanelChatControl.

Actually, maybe this could even be a setting in the same chat control, i.e. `<control name="nifty-chat" type="de.lessvoid.nifty.controls.ListBox" />` via xml, or `type (ScrollPanel.class);` in java builder.

**Comment by Joris-van-der-Wel** [comment]
> Ah, it's all clear now. Does not specifying the width and/or height still work as expected? What about images instead of panels, and images within panels? Are those properly dealt with under this improved system?

The original behaviour is covered by test cases, but I have also tried them myself in xml (and it works).

Images appear to work as expected, I did not know images could be parents of things though. I just tried them and if an image does not have children, the width and height defaults to the actual image size. If you give them children, the defaults depend on the children. This is pretty much what I would expect, looking at the code.

**Comment by void256** [comment]
@Joris-van-der-Wel Wow, that's quite a lot of work and changes! Thanks! :smile:

I have to admit that I have some fear that some of your changes will eventually break existing user code. Layout in Nifty is a sensible thing :wink: So at the moment I hesitate a bit to apply the pull request as-is. Especially since it contains several changes all at once. And to be honest, I don't understand all of them and their consequences in full detail.

If I apply that pull request, would you be able to be around for layout specific support if others encounter any issues with this?

**Comment by Joris-van-der-Wel** [comment]
@void256 I debated a lot whether or not I should change existing behaviour. I actually started out with not changing any existing behaviour, but this led to a bit of a mess, especially in SizeValue.java and Element.java.

I can see user code breaking in the following ways:
- Their code relies on getConstaintWidth/Height() on returning null so that they can augment the "default" behaviour which applies to vertical and horizontal layouts. All they would have to do is change "== null" to ".hasDefault()"
- They are interpreting SizeValue.toString() which no longer returns null when a null was passed in the constructor. toString never returns null now.
- They are not expecting "sum" and "max" values in SizeValue.
- They are not expecting the extra prepareLayout(); and processLayout(); call (which is needed for &lt;text width="*" wrap="true"/&gt;), which would seem to me a very rare issue because it is internal to nifty. 

I think that if any issue occurs, it will be related to user code accessing the "default" width and height SizeValues (unset width/height xml attribute).

This patch comes with a 1 year warranty :yum:. I'll add a watch for this project.

**Comment by void256** [comment]
The 1 year warranty argument convinced me :wink: I'm applying the patch! Thanks for your work and the service contract :smile:

**Comment by devinep52** [comment]
@Joris-van-der-Wel I was working on extending your scrollpanel example to provide "chat box" functionality, but failed  to get my scroll panel to update correctly (the added panel was not being clipped when scrolling).  Did you ever get around to finishing a scrollpanel chatbox?

**Comment by Joris-van-der-Wel** [comment]
It is still on the todo, currently I am focusing on some tasks in my project which have a higher priority.

Anyways I have an example running (the one from the screenshot) where in the clipping works correctly (I pulled 1.4 a few mins ago).

Perhaps you could put up an example somewhere so I can try it?
If you are adding elements dynamically you might need to call layoutElements() on the parent element. Another way to test this is to keep calling nifty.resolutionChanged() which will reflow everything.

**Comment by devinep52** [comment]
Sure, here's the code for the control from your example, pous a textfield and append button

```
<panel width="423" childLayout="vertical" backgroundColor="#444f" align="center" valign="center">
            <control id="scrollbarPanel" style="special-scrollpanel" name="scrollPanel" horizontal="false" height="400" width="100%" childLayout="vertical">
                    <panel id="myScrollStuff" width="100%" childLayout="vertical">
                            <panel  width="100%" height="max" backgroundColor="#f00f" childLayout="horizontal" align="center">
                                    </panel>
                            <panel height="50"/>
                            <panel width="100%" height="max" backgroundColor="#f00f" childLayout="horizontal" align="center">
                                    <panel valign="center" backgroundColor="#0f0f" width="60" height="60"/>
                                    <text valign="center" width="*" style="nifty-label" backgroundColor="#00ff" color="#000f" wrap="true" text="Ut non pretium urna. Ut faucibus diam eu commodo auctor. Phasellus lobortis felis eu velit blandit, quis volutpat turpis dictum. Vivamus massa nibh, dignissim non fringilla vitae, euismod sit amet lacus. Duis tristique, dui non consequat tempus, justo nunc feugiat sapien, eu ornare ligula turpis eu velit."/>
                            </panel>
                            <panel height="50"/>
                            <panel width="100%" height="max" backgroundColor="#f00f" childLayout="horizontal" align="center">
                                    <text valign="center" width="*" style="nifty-label" backgroundColor="#00ff" color="#000f" wrap="true" text="Ut non pretium urna. Ut faucibus diam eu commodo auctor. Phasellus lobortis felis eu velit blandit, quis volutpat turpis dictum. Vivamus massa nibh, dignissim non fringilla vitae, euismod sit amet lacus. Duis tristique, dui non consequat tempus, justo nunc feugiat sapien, eu ornare ligula turpis eu velit."/>
                                    <panel valign="top" backgroundColor="#0f0f" width="60" height="60"/>
                            </panel>
                            <panel height="50"/>
                            <panel id="panelhere" width="100%" height="max" backgroundColor="#f00f" childLayout="horizontal" align="center">
                                    <text valign="center" width="*" style="nifty-label" backgroundColor="#00ff" color="#000f" wrap="true" text="Ut non pretium urna. Ut faucibus diam eu commodo auctor. Phasellus lobortis felis eu velit blandit, quis volutpat turpis dictum. Vivamus massa nibh, dignissim non fringilla vitae, euismod sit amet lacus. Duis tristique, dui non consequat tempus, justo nunc feugiat sapien, eu ornare ligula turpis eu velit."/>                                
                            </panel>
                    </panel>

            </control>
            <panel width="100%" childLayout="horizontal">
                        <control id="addTextField" name="textfield" maxLength="200" />
                        <control id="appendButton" name="button" label="Send" />
            </panel>
    </panel>
```

And this is what I put in my append button subscriber in the controller:

```
Element panel = screen.findElementById(“myScrollStuff”);
panel.addChild(
        new PanelBuilder() {{
            width(“100%”);
            height(“max”);
            backgroundColor(“#f00f”);
            childLayoutHorizontal();
            valignCenter();

            text(new TextBuilder() {{

                width(“*”);
                wrap(true);
                font(“aurulent-sans-16.fnt”);
                color(“#ffff”);
                text(addTextField.getRealText());
                alignLeft();
                valignCenter();
                }});
            panel(new PanelBuilder() {{
                valignTop();
                backgroundColor(“#fFFf”);
                width(“60″);
                height(“60″);
            }});
        }}.build(nifty, screen, screen.findElementById(“foreground”))
        );

    Element panelt = screen.findElementById(“scrollbarPanel”);
        panel.layoutElements();
        panelt.layoutElements();
        ScrollPanel panels = (ScrollPanel)panelt;

        panels.setUp(0, 5, 0, 50, AutoScroll.OFF);
```

I also tried adding the child to the content root ("#nifty-scrollpanel-child-root") but nothing happened.  It's strange that it works perfectly from static xml, but when I use the builder at runtime it won't clip it...other than that it works fine :P

**Comment by devinep52** [comment]
I have another finding to share. If I do something like:

```
CreateLabelControl label = new CreateLabelControl(text);
label.create(nifty, screen, myScrollStuff);
```

At runtime, then the label gets added and clipped just fine!  If I replace that with:

```
TextCreator texter = new TextCreator(text);
texter.create(nifty, screen, myScrollStuff);
```

Then nothing happens... So again, I'm stuck with unwrapped text in the chat panel.  Maybe if you could point me to where the clipping is done in the source then I can step through and try to find out why it's not being called correctly?  I've scoured the runtime variables for any difference (those that were created statically and those at runtime) and have come up with nothing still.

**Comment by devinep52** [comment]
Alright, final update.  I still failed to find any way to clip new panels, so instead I'm just getting the text renderer and appending all of my chat text.  It would be nice to have image icons with the text, so if anyone solves this problem before I get some time to dig into this more then that's great.

Thanks for the help so far in this Joris and Void!  When I'm done working out the kinks on this then I can send in the new ListPanelChatbox with wrapping text as a patch.

**Comment by Joris-van-der-Wel** [comment]
I am not sure about what is going on with TextCreator either. If I debug it, it has no TextRenderer added to it (look at element.elementRenderer). Maybe you could test TextCreator in isolation and add an issue?

Anyway I've got that first example to work using the PanelBuilder just fine, including wrapping, that extra white panel and the width=max is also working as espected.

``` java
final TextField addTextField = screen.findElementById("addTextField").getNiftyControl(TextField.class);
final Element myScrollStuff = screen.findElementById("myScrollStuff");
final Element scrollbarPanel = screen.findElementById("scrollbarPanel");
assert addTextField != null;
assert myScrollStuff != null;
assert scrollbarPanel != null;

final String content = addTextField.getRealText();

myScrollStuff.addChild(new PanelBuilder()
{{
        width("100%");
        height("max");
        backgroundColor("#f00f");
        childLayoutHorizontal();
        valignCenter();

        text(new TextBuilder()
        {{
                width("*");
                wrap(true);
                font("aurulent-sans-16.fnt");
                color("#ffff");
                text(content);
                alignLeft();
                valignCenter();              
        }});
        panel(new PanelBuilder()
        {{
                valignTop();
                backgroundColor("#fFFf");
                width("60");
                height("60");     
        }});
}}.build(nifty, screen, myScrollStuff));

scrollbarPanel.layoutElements();

ScrollPanel scrollPanel = scrollbarPanel.getNiftyControl(ScrollPanel.class);
scrollPanel.setVerticalPos(Float.MAX_VALUE);
```

Perhaps something went wrong with git/build process/IDE? You could try pulling 1.4 into a clean directory to see if that helps.

**Pull request merged**
