### PR TITLE
Updated Processing Renderer and Minim Soundsystem to Processing 3.0.1

### PR DESCRIPTION
**Pull request by barefists**
Cleaned up and resubmitting the changes.

### CODE REVIEW

**Comment by bgroenks96** [comment]
Looks good. Not trying to be too picky... but... :wink: 

1) Could you get rid of all of those eclipse files and add them to the .gitignore in your new module?
2) You did test the examples, right? xD

**Comment by barefists** [comment]
Done.
Yep, I tested everything and posted a version on the Processing forums. Barring bugs reported by the community, it should be good to go. :)

**Comment by bgroenks96** [comment]
Looks like there are still some eclipse files floating around in the soundsystem module :cry:

**Comment by barefists** [comment]
Updated. :)

**Comment by bgroenks96** [comment]
Great! Thanks for your work! :+1:

**Comment by barefists** [comment]
No worries, I find hobby coding exceedingly relaxing. ;)

**Pull request merged**
