### PR TITLE
Added methods to listbox to retrive Scrollbars.

### PR DESCRIPTION
**Pull request by relu91**
Whith this you are able to set buttonStepSize and PageStepSize in the listbox. this solves #107 because in the Scrolpanel they were already implemented methods to set this values. Sorry for the delay :package:

### CODE REVIEW

**Comment by ghost** [comment]
@relu91 You're code commits don't line up with the code style of the rest of the library. Every time I encounter your code I end up having to fix the style and formatting. I'd appreciate it if you could be more careful in the future.

@void256 If you could check code in pull requests for quality (spelling errors, formatting errors, code style violations, deeply nested if statements, all stuff I've found in some recent merged PR's), and ask them to be fixed before merging, I'd greatly appreciate it.

This one isn't as bad as some others, but an empty `@Return` in the javadoc? Missing blank lines between methods? Come on.

**Comment by NetzwergX** [comment]
@3xp0n3nt @void256 You could put up a CONTRIBUTING.md (https://github.com/blog/1184-contributing-guidelines) which lays out all these points.

**Comment by relu91** [comment]
Sorry I don't even know that there was a checkstyle file .... I will take more attention in the future! Anyway I understand your frustration but there's no reason to be rude :smiley:

**Comment by ghost** [comment]
> 3xp0n3nt commented 2 days ago 
> I'd appreciate it if you could be more careful in the future.
> 
> > relu91 commented a day ago 
> > there's no reason to be rude

From my perspective I was being polite. Sorry if I offended you.

**Comment by ghost** [comment]
> NetzwergX commented 2 days ago
> 
> @3xp0n3nt @void256 You could put up a CONTRIBUTING.md (https://github.com/blog/1184 contributing-guidelines) which lays out all these points.

While that would be ideal, it's extremely easy to simply copy the style of the rest of the code. I've never read any style guidelines for Nifty Gui, I just looked at the surrounding code. Because it's so easy, then not doing it seems to convey laziness rather than a lack of understanding.

**Comment by relu91** [comment]
I was talking about these lines :

> This one isn't as bad as some others, but an empty @Return in the javadoc? Missing blank lines between methods? Come on.

Anyways don't worry, I'm here to help , but most of all to learn ( you know I'm still studying ) and I didn't get used to check my code style , so thank you for the lesson :)

**Comment by ghost** [comment]
@relu91 I thought everyone already knew about using the style of the surrounding code - if you didn't know, then I'm sorry, I would have been less critical and more teaching ;-).

**Pull request merged**
