### PR TITLE
Some issues fixed

### PR DESCRIPTION
**Pull request by relu91**
Hi , I worked on this issues #53 , #176 and #175 . About #53 this is a first implementation indeed it works only for primary button but I tested it and it worked fine . The behavior is : click-click-click will fire onPrimaryClickEvent - MultiClickEvent( count = 2 ) - MultiClickEvent( count = 3 ) . I used this implementation because is similar to swing one . I leave "single click event" because I don't know if this will in some way break the current users assumptions . 
I see in the commits that two entire classes are overridden I don't know why .... do you know how I could solve this ?

### CODE REVIEW

**Comment by void256** [comment]
Good work! I'm ok with commit 92727ce :smile:

But I can't apply 9acfdf2 as-is because I can't see what you have changed, I'm sorry. The ElementInteractionClickHandler, MouseClickMethods and PrimaryClickMouseMethods classes look like as you would have changed each line. Can you please check this again? It might be just a "new line" setting in your IDE or did you reformat the complete file eventually? Not a good idea because one can't see what has changed in these files at all :smile:

And I think it would be helpful if you could merge your branch before applying your changes and creating the pull request. So that only your changes appear in the pull request?

**Comment by relu91** [comment]
Ok @void256 , sorry about https://github.com/void256/nifty-gui/commit/9acfdf2 , I think is eclipse fault , because I only edited some lines of those files. So do you know which are the steps to revert my changes safely ? I mean not completely re-write all the commit but only edit those files . About merge , I used github client , I opened a console e simple fetch your repo and then merge mine with yours... but I see that now, in the pull there's also your commits do you know why? where I am wrong ? .
Sorry about this noob questions but every time I feel that I know everything about git , suddenly I found that I am completely wrong! :D 

Thanks

**Comment by relu91** [comment]
Oh , i forget an other question :P . Is there a way to store some global values in Nifty-gui? . I know that it's hard to see but in this commit https://github.com/void256/nifty-gui/commit/9acfdf2 I used a threshold value to know when I stop to record multi click events . I think that this value should be configurable by the nifty user . Any suggestion ? :)

**Comment by void256** [comment]
**About global values**
There is nifty.getGlobalProperties() which returns a Properties instance which you could use for that purpose :smile: It was not really meant for that because it's purpose was to store key/values for special values replace mechanism using the `${PROP.key}` in attributes BUT I don't really see why you can't use it for your purpose as well :smile:

**About fixing your pull request**
I'm not sure if you can do it without rewriting your changes. But I think you should be able to pull the original branch into yours which should make my commits disappear from your pull request, something like: `git pull nifty-origin 1.4` I'm not sure how you do that and especially how your remote is called (nifty-origin). But the basic idea is to pull in all of the 1.4 changes into your fork before creating the pull request, I think.

About fixing the new lines in these files ... I'm not sure how you can do that without rewriting your changes. Can you diff them local and see what you've changed? In that case I would suggest reverting your changes and then reapplying them manually without changing the new lines automatically. I don't think there is an automatic way to do that tho...

**Comment by relu91** [comment]
Thanks! this afternoon I'm going to solve this. I also found out why those three file are all modified ! I used auto format code in eclipse.... and it might change the whole file ... shame on me -.-" :)

**Comment by relu91** [comment]
It seems that git hates me ... On my local repo all is fine ... but when i push in my remote forked repository the whole file is changed -.-" . Maybe should I  close this pull request first ?

**Comment by NetzwergX** [comment]
Looks like an issue with line endings? https://help.github.com/articles/dealing-with-line-endings

**Comment by relu91** [comment]
I don't if it was line endings , I changed an option in my git client ( Use rebase for pull ) . Now files are ok :) . Is it ok even if there are a couple of new commits ? anyway thanks @NetzwergX

**Comment by void256** [comment]
Looks better now @relu91 :smile: Thanks for cleaning it up!

**Pull request merged**
