### PR TITLE
Example of issue 100

### PR DESCRIPTION
**Pull request by relu91**
A simple main to test issue 100 . You can choose between Italian , German , French and the system default.

### CODE REVIEW

**Comment by void256** [comment]
I've found my stash and it already had an example for issue 100. I'll close this for now and hope you don't mind :smile:

**Comment by void256** [comment]
... but not all is lost! I've used the DropDown from your example now since mine only had a couple of buttons :smile:

**Comment by relu91** [comment]
Ok ok ! :smile: I didn't spend so much time on this, so don't worry ! I hope that you can fix the issue . Also would be cool that even that the other "special values" can be automatically updated when you change them on the java side . Like when you change a property in globalProperties also all the elements receive that change , but I think this is even more difficult to achieve since it requires a sort of DataBinding ...  Well just some thoughts :smile:

**Comment by void256** [comment]
Yes, would be nice but I don't see that happening for all attributes - it's getting too complicated :/

I have it working for TextRenderer now which means all texts can be replaced when the locale is being changed :smile: I'm about to commit that in a couple of minutes ...

**Pull request closed without merging**
