### PR TITLE
Refactor Nifty Examples.

### PR DESCRIPTION
**Pull request by ghost**
- Move all LWJGL content in nifty-examples module to it's own new
  module, nifty-examples-lwjgl. LWJGL isn't special - it can have its own
  examples module just like everyone else.
- Remove nifty-renderer-lwjgl dependency from nifty-examples.
- Refactor LWJGL initialization code in nifty-examples-lwjgl to make it
  stupid-easy to load & run any NiftyExample in one line of code (hint:
  it's easier than Slick2D, and that's difficult to beat)
- nifty-examples-lwjgl now implements every single example found in
  nifty-examples
- Cleanup & refactor the code in many of the examples in nifty-examples.
  TODO: Many more examples still need a ton of cleanup though!
- Delete the "issues" package & classes out of nifty-examples:
  
  This has got to be the most horrible idea I've seen in Nifty in a long
  time. It reeks of laziness. First of all, there's the problem of
  unsustainability. What's going to happen as the number of these issues
  keeps growing? At some point it's going to get nasty. It increases the
  size of the Nifty Gui library as well.
  
  Secondly, all those issues have been resolved! Who wants to see a bunch
  of code demonstrating non-existent problems? Probably no one.
  
  Who's going to want to maintain & update code for non-existent issues in
  the future when the examples or other code needs refactoring? _Cricket,
  cricket_ That's what I thought. I've refactored the Nifty examples, and
  in the process, I've broken these stupid issues classes. Guess how much
  motivation I have to fix them?
  
  If you want to create demonstrations of bugs, please maintain your own
  repository for such things. In fact, why not have a public nifty-issues
  repository for this? There, problem solved.
- Delete the top-secret, uber-special "meins" file. It's from 2008, and
  it looks like @void256's personal notes or something? Doesn't belong
  in Nifty Gui.
- Add some missing examples to nifty-examples-slick2d (tutorial,
  multiclick, healthimage), since it's insanely easy to add new examples
  (thanks to @mkaring).
- Unrelated: Fix Slick2D naming inconsistencies. Some modules / packages
  / comments / etc use the word "slick", some use the word "slick2d",
  and still others use the word "slick2D". Rename comments & text mentions
  Slick2D, for package names & module names that require lowercase, use
  slick2d everywhere.
- Note: Slick2D still has some pre-existing unresolved issues, such as
  certain examples crashing due to "java.lang.NoClassDefFoundError:
  com/jcraft/jorbis/Info" (music issue?).
- Unit tests & integration tests are successful (excluding all the
  pre-existing examples issues - what I mean is that the changes did not
  introduce any bugs / regressions as far as could be tested).

### CODE REVIEW

**Comment by relu91** [comment]
Great work! :) What about of a wiki page describing how to implement an Example if a developer adds a new feature in nifty? :smiley: I hope I'm not annoying you XD

**Comment by ghost** [comment]
@relu91 No you're not annoying me lol. I'll add that information soon.

**Comment by void256** [comment]
Yep, great work indeed! And I always very much appreciate the @3xp0n3nt detailed commit messages a lot :+1: :+1: :+1: 

I hope that the removal of the super secret "meins" file will not make Nifty explode now :grin: - reading about that in the commit comment made me actually LOL :wink: I think it's the settings file for some angel code font generator but I can't remember any details so it's okay that it's being removed :wink: 

Well, I agree with the comments about the "issues" package being hard to maintain and in case issue numbers change it will become a nightmare ... BUT ... on the other hand I still think having that package was really an excellent idea :yum:

First it shows others what a SSCCE has to look like and I was very very happy as, I think it was @relu91, added one for some issue he posted :smile: and second it was meant to be kept as like an extended suite of manual test cases as some form of regression testing.

So, I understand you have issues with the issue package :wink: but I'm not so happy with it's removal. I don't see any issue with "code size" since it was only part of the nifty-examples project and not the main library. I think we need the public nifty-issues repository for that. Especially for the cases that someone wants to post an issue. Having existing issues **with** example code would really be a great example for that.

**Comment by ghost** [comment]
@void256 Thanks so much for merging. I understand about the issues thing. They ARE valuable. I didn't mean to imply that they weren't. I just think they were misplaced :P. We should DEFINITELY have a nifty-issues repository, I think that would be an awesome idea, and very helpful.

**Comment by ghost** [comment]
@void256 Re-reading my rant in the commit message about the issues package, it was a little over the top, lol. I think I was just pissed off about it in the moment, you know? It doesn't seem like such a big deal now, although I still think it's a good idea to separate it out of the library.

**Pull request merged**
