### PR TITLE
Add method to get panel background color.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by oberien** [comment]
Thank's so much! :) :+1:

**Comment by ghost** [comment]
@Blackhole16 If you don't want to wait for @void256 to merge, you can always do [this](http://stackoverflow.com/questions/8891339/github-how-to-add-open-pull-requests-to-local-repo?lq=1) (or [this](http://stackoverflow.com/questions/6022302/pull-requests-from-other-forks-into-my-fork)).

**Comment by oberien** [comment]
I think/hope void256 will merge this pull soon. If i wait until he does so and if I download and compile the 1.4.1-ALPHA with this pull request implemented, will it actually work, or are there still too much issues so I should stay with 1.4 and implement one of my own solutions?

**Comment by ghost** [comment]
1.4.1-SNAPSHOT is really stable and usually has the latest bugfixes. I highly
recommend it if you're comfortable with working & building from source.

Aaron Mahan
Co-Founder & CEO
Forerunner Games, LLC
http://forerunnergames.com/
Peril: http://perilgame.com/

**Comment by relu91** [comment]
Also if you are not working from source I suggest to use gradle or even maven for project management it's really simple to get the latest build.

**Comment by relu91** [comment]
@void256  is back! :


lol

**Comment by oberien** [comment]
WB void :) Thanks for merging.

ps: of cause i mean @void256 and not "nothing" ;D

**Pull request merged**
